name: Shimmer Build & Test CI

on:
  push:
    branches: [ main, ci-failure-shim ]
  pull_request:
    branches: [ main ]

jobs:
  fail_build:
    name: Build without required env (Expected Failure)
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Java 11 (server)
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '11'

      - name: Setup Node.js 16 (console)
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y maven npm

      - name: Configure & build server (expected to fail if config missing)
        run: |
          # adjust path if server is in a subfolder, e.g., cd server
          mvn -B -DskipTests install

      - name: Build console (won't reach if server step fails)
        run: |
          # adjust path if console is in subfolder, e.g., cd console
          npm ci
          npm run build

  pass_build:
    name: Build with dependencies (Expected Success)
    runs-on: ubuntu-22.04

    services:
      mongodb:
        image: mongo:5.0
        ports:
          - 27017:27017
        options: --health-cmd="mongosh --eval 'db.adminCommand(\"ping\")'" --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Java 11 (server)
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '11'

      - name: Setup Node.js 16 (console)
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y maven npm

      - name: Wait for MongoDB
        run: |
          for i in `seq 1 30`; do
            nc -z localhost 27017 && break || sleep 1
          done

      - name: Build server
        run: |
          # adjust to actual server folder if required
          mvn -B -DskipTests install

      - name: Run server tests
        run: |
          mvn test || true

      - name: Build console
        run: |
          # adjust to actual console folder if required
          npm ci
          npm run build
