name: Shimmer CI

on:
  push:
    branches: ["**"]         # Run on every push to any branch
  pull_request:               # Run on all PRs

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-22.04

    services:
      mongodb:
        image: mongo:5.0
        ports:
          - 27017:27017
        options: --health-cmd="mongosh --eval 'db.adminCommand(\"ping\")'" --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Java 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '8'

      - name: Set up Gradle
        uses: gradle/wrapper-validation-action@v2

      - name: Build with Gradle
        run: |
          ./gradlew clean build -x test

      - name: Run Tests
        run: |
          ./gradlew test
