name: Shimmer CI

on:
  push:
    branches: ["**"]         # run on every push to any branch
  pull_request:               # run on all PRs

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-22.04

    services:
      mongodb:
        image: mongo:5.0
        ports:
          - 27017:27017
        options: --health-cmd="mongosh --eval 'db.adminCommand(\"ping\")'" --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Java 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '11'

      - name: Setup Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y maven npm

      - name: Build server
        run: |
          cd shimmer-resource-server   # <<-- replace this with correct subfolder containing pom.xml
          mvn clean install -DskipTests

      - name: Run server tests
        run: |
          cd shimmer-resource-server
          mvn test

      - name: Build console
        run: |
          cd console                  # <<-- replace with correct console folder if needed
          npm ci
          npm run build
